#ddev-generated
services:
  elasticvue:
    container_name: ddev-${DDEV_SITENAME}-elasticvue
    image: cars10/elasticvue
    restart: "no"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=5610:8080
      - HTTPS_EXPOSE=5611:8080
      - "ELASTICVUE_CLUSTERS=[{\"name\":\"docker-cluster\",\"uri\":\"https://${DDEV_SITENAME}.${DDEV_TLD}:9201\"}]"
    depends_on:
      - elasticsearch

  # Set the necessary environment variables to access the Elasticsearch API.
  elasticsearch:
    environment:
      - http.cors.enabled=true
      - "http.cors.allow-origin=*"
